apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-deployer
  namespace: poltr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gha-deployer-role
  namespace: poltr
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","patch","update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-deployer-rb
  namespace: poltr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gha-deployer-role
subjects:
  - kind: ServiceAccount
    name: gha-deployer
    namespace: poltr
