import hmac
import secrets
import json
import os
from datetime import datetime, timedelta
from typing import Literal
from fastapi.responses import JSONResponse
from pydantic import BaseModel, EmailStr
import src.core.db as db
from src.core.email_service import email_service
from src.auth.auth_email_guard import auth_email_capped, record_auth_email_sent
from src.auth.middleware import hash_token
from src.auth.email_hmac import email_digest

# Short code config: no ambiguous chars (0/O, 1/I/L)
SHORT_CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
SHORT_CODE_LENGTH = 6
MAX_FAILED_ATTEMPTS = 5

# Magic-link / short-code validity for the unified ch.poltr.auth.start flow.
# One value for both branches so the flow is indistinguishable to the user
# before the email arrives.
MAGIC_LINK_TTL_MINUTES = 10

# Per-email send throttle (anti email-bombing), applied on top of the per-IP
# slowapi limit. At most MAX_SENDS_PER_EMAIL emails to one address per window.
# See doc/SECURITY_AUTH.md #2.
MAX_SENDS_PER_EMAIL = 10
SEND_WINDOW_MINUTES = 15

def generate_short_code() -> str:
    return "".join(secrets.choice(SHORT_CODE_ALPHABET) for _ in range(SHORT_CODE_LENGTH))


def safe_return_url(url: str | None) -> str | None:
    """Only accept same-origin relative paths (open-redirect guard).

    The frontend later does router.push() on this value, so an absolute or
    protocol-relative URL (//evil.com) must never be stored. Auth/root paths are
    pointless to return to and would loop, so they are rejected too.
    """
    if not url or not isinstance(url, str):
        return None
    if not url.startswith("/") or url.startswith("//") or url.startswith("/\\"):
        return None
    if url == "/" or url.startswith("/auth/"):
        return None
    return url


class StartData(BaseModel):
    """Unified entry point: one email field, no login/register distinction.

    `initiatorSecret` is generated by the frontend and stored hashed in the
    pending row, so the later magic-link preflight can recognise the originating
    browser. The frontend keeps the secret in a httpOnly cookie.
    """
    email: EmailStr
    returnUrl: str | None = None
    initiatorSecret: str | None = None


class CheckLinkData(BaseModel):
    """Non-consuming preflight for the unified /auth/verify page."""
    token: str
    initiatorSecret: str | None = None


class WaitStatusData(BaseModel):
    """Polling payload for the waiting screen (browser A)."""
    initiatorSecret: str | None = None


class VerifyLoginMagicLinkData(BaseModel):
    token: str
    initiatorSecret: str | None = None


class VerifyRegistrationMagicLinkData(BaseModel):
    token: str
    initiatorSecret: str | None = None


class VerifyShortCodeData(BaseModel):
    email: EmailStr
    code: str
    initiatorSecret: str | None = None
    # Kept for backward compatibility with the deprecated split flow; the unified
    # handler is purpose-agnostic and ignores it (it searches both tables).
    purpose: Literal["login", "registration"] = "login"


def _initiator_matches(secret: str | None, stored_id: str | None) -> bool:
    """Device binding: the login is only completable in the browser that started
    it. True iff the request's initiator cookie hashes to the pending row's
    `initiator_id`. Rows without an `initiator_id` (legacy rows predating the
    unified start flow) are NOT bound and pass through.
    See doc/SECURITY_AUTH.md."""
    if stored_id is None:
        return True
    if not secret:
        return False
    return hmac.compare_digest(hash_token(secret), stored_id)


def _different_browser_response() -> JSONResponse:
    return JSONResponse(
        status_code=403,
        content={
            "error": "different_browser",
            "message": "This link must be completed on the device where you started.",
        },
    )


# ─── Unified flow (ch.poltr.auth.start / checkLink / waitStatus) ──────────────

def _neutral_start_response(initiator_secret: str) -> JSONResponse:
    """Identical response for login AND registration so the user sees no
    difference before the email arrives. `initiatorSecret` is always returned
    (even on throttle/cap) to keep the shape constant; the frontend stores it in
    a httpOnly cookie. See doc/SECURITY_AUTH.md."""
    return JSONResponse(
        status_code=200,
        content={
            "success": True,
            "message": "If this email can sign in, a link has been sent.",
            "initiatorSecret": initiator_secret,
        },
    )


# Both pending tables are UNIQUE(email_hmac) and share the identical per-email
# throttle upsert; only the table name differs. `table` is an internal literal
# (one of two constants below, never user input), so interpolating it is
# injection-safe. Centralising it keeps the two branches from drifting — the
# must-match throttle predicate lives in exactly one place. See doc/SECURITY_AUTH.md #2.
async def _upsert_pending_send(
    conn,
    table: str,
    *,
    email_hmac: str,
    token: str,
    short_code: str,
    return_url: str | None,
    expires_at: datetime,
    initiator_id: str,
) -> int:
    """Collapse to ONE live token/code for this email AND advance the per-email
    window counter atomically. The upsert rotates the token (resetting
    failed_attempts → the 5-attempt brute-force cap can't be multiplied by
    re-requesting) and increments send_count within the window. NB: counting rows
    instead would be a no-op — one live row pins the count at 1. Returns the new
    send_count."""
    return await conn.fetchval(
        f"""
        INSERT INTO {table}
            (email_hmac, token, short_code, return_url, expires_at, initiator_id)
        VALUES ($1, $2, $3, $4, $5, $6)
        ON CONFLICT (email_hmac) DO UPDATE SET
            token = EXCLUDED.token,
            short_code = EXCLUDED.short_code,
            return_url = EXCLUDED.return_url,
            initiator_id = EXCLUDED.initiator_id,
            failed_attempts = 0,
            expires_at = EXCLUDED.expires_at,
            send_count = CASE
                WHEN {table}.window_started_at > now() - ($7 || ' minutes')::interval
                THEN {table}.send_count + 1 ELSE 1 END,
            window_started_at = CASE
                WHEN {table}.window_started_at > now() - ($7 || ' minutes')::interval
                THEN {table}.window_started_at ELSE now() END
        RETURNING send_count
        """,
        email_hmac, token, short_code, return_url, expires_at, initiator_id,
        str(SEND_WINDOW_MINUTES),
    )


async def start_handler(
    data: StartData, locale: str = "de", initiator_secret: str | None = None
) -> JSONResponse:
    """Unified send: decide login vs registration internally and email the right
    text. The only branch visible to anyone is *which email* goes out — the HTTP
    response is identical either way (enumeration-safe).
    """
    try:
        if db.pool is None:
            await db.init_pool()

        email = data.email.lower()          # plaintext — used ONLY to send the mail
        email_h = email_digest(email)       # peppered HMAC — everything stored/queried
        return_url = safe_return_url(data.returnUrl)
        secret = initiator_secret or secrets.token_urlsafe(32)
        initiator_id = hash_token(secret)

        # Global hourly circuit breaker — neutral, reveals nothing.
        if await auth_email_capped():
            return _neutral_start_response(secret)

        token = secrets.token_urlsafe(32)
        short_code = generate_short_code()
        expires_at = datetime.utcnow() + timedelta(minutes=MAGIC_LINK_TTL_MINUTES)

        async with db.pool.acquire() as conn:
            account = await conn.fetchrow(
                "SELECT 1 FROM auth_creds WHERE email_hmac = $1", email_h
            )
            is_login = account is not None

            # One live code per email + per-email window throttle, identical for
            # both branches (only the target table differs). See _upsert_pending_send.
            table = "auth_pending_logins" if is_login else "auth_pending_registrations"
            send_count = await _upsert_pending_send(
                conn,
                table,
                email_hmac=email_h,
                token=token,
                short_code=short_code,
                return_url=return_url,
                expires_at=expires_at,
                initiator_id=initiator_id,
            )
            if send_count > MAX_SENDS_PER_EMAIL:
                return _neutral_start_response(secret)
            purpose = "login" if is_login else "registration"

        # Email carries ONLY the magic link now — no short code (the code is shown
        # in-browser only when the link opens in a different browser).
        success = email_service.send_confirmation_link(
            email, token, purpose=purpose, locale=locale
        )
        if not success:
            return JSONResponse(
                status_code=500,
                content={"error": "email_failed", "message": "Failed to send email"},
            )

        await record_auth_email_sent(purpose)
        return _neutral_start_response(secret)

    except Exception as e:
        print(f"start_handler error: {e}")
        return JSONResponse(
            status_code=500, content={"error": "internal_error", "message": str(e)}
        )


async def check_link_handler(data: CheckLinkData) -> JSONResponse:
    """Non-consuming preflight. Finds the pending row by token in BOTH tables and
    reports same-browser vs different-browser. The short code is revealed ONLY in
    the different-browser case (to be typed on the originating device)."""
    if db.pool is None:
        await db.init_pool()

    token = data.token
    async with db.pool.acquire() as conn:
        row = None
        purpose = None
        for table, p in (
            ("auth_pending_logins", "login"),
            ("auth_pending_registrations", "registration"),
        ):
            row = await conn.fetchrow(
                f"""
                SELECT email_hmac, short_code, expires_at, initiator_id
                FROM {table} WHERE token = $1
                """,
                token,
            )
            if row:
                purpose = p
                break

        if not row:
            return JSONResponse(
                status_code=400,
                content={"error": "invalid_token", "message": "Invalid or expired link"},
            )
        if datetime.utcnow() > row["expires_at"]:
            return JSONResponse(
                status_code=400,
                content={"error": "token_expired", "message": "This link has expired"},
            )

        same_browser = (
            bool(data.initiatorSecret)
            and bool(row["initiator_id"])
            and hmac.compare_digest(hash_token(data.initiatorSecret), row["initiator_id"])
        )

        # Identity for the cross-device screen. We no longer store the plaintext
        # email, so for a LOGIN we show the pseudonym (Bergname + Profil-Infos)
        # looked up via the email HMAC. For a REGISTRATION no profile exists yet
        # → null (the frontend shows a generic, name-less message).
        profile = None
        if purpose == "login":
            prow = await conn.fetchrow(
                """
                SELECT p.display_name, p.mountain_fullname, p.canton, p.height, p.color
                FROM auth_creds c
                JOIN app_profiles p ON p.did = c.did
                WHERE c.email_hmac = $1
                """,
                row["email_hmac"],
            )
            if prow:
                profile = {
                    "displayName": prow["display_name"],
                    "mountainFullname": prow["mountain_fullname"],
                    "canton": prow["canton"],
                    "height": float(prow["height"]) if prow["height"] is not None else None,
                    "color": prow["color"],
                }

        result = {
            "status": "same" if same_browser else "different",
            "purpose": purpose,
            "profile": profile,
        }
        if not same_browser:
            # Revealed only to whoever holds the link (= controls the inbox). Shown
            # on the link device, typed on the originating device. See SECURITY_AUTH.md.
            result["code"] = row["short_code"]
        return JSONResponse(status_code=200, content=result)


async def _session_is_valid(token: str | None) -> bool:
    """Lightweight, non-raising session check for the polling endpoint."""
    if not token:
        return False
    if db.pool is None:
        await db.init_pool()
    async with db.pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT expires_at FROM auth_sessions WHERE session_token = $1",
            hash_token(token),
        )
    return bool(row) and datetime.utcnow() <= row["expires_at"]


async def wait_status_handler(
    data: WaitStatusData, session_token: str | None
) -> JSONResponse:
    """Polling status for the waiting screen (browser A): authenticated (login
    completed in another tab) | pending (link still live) | gone (expired or
    already used). Drives A's auto-advance and the 'request a new link' state."""
    if await _session_is_valid(session_token):
        return JSONResponse(status_code=200, content={"state": "authenticated"})

    if data.initiatorSecret:
        if db.pool is None:
            await db.init_pool()
        initiator_id = hash_token(data.initiatorSecret)
        async with db.pool.acquire() as conn:
            row = await conn.fetchrow(
                """
                SELECT return_url FROM auth_pending_logins
                    WHERE initiator_id = $1 AND expires_at > now()
                UNION ALL
                SELECT return_url FROM auth_pending_registrations
                    WHERE initiator_id = $1 AND expires_at > now()
                LIMIT 1
                """,
                initiator_id,
            )
        if row:
            return JSONResponse(
                status_code=200,
                content={"state": "pending", "returnUrl": row["return_url"]},
            )

    return JSONResponse(status_code=200, content={"state": "gone"})


async def verify_login_magic_link_handler(
    data: VerifyLoginMagicLinkData,
) -> JSONResponse | tuple[str, str | None] | None:
    """Verify magic link token and create session.

    Returns (email, return_url) on success — return_url is the path the user
    originally wanted (or None), so the route can hand it back to the frontend.
    """
    if db.pool is None:
        print("Pool is None, initializing now...")
        await db.init_pool()
        print("Pool initialized successfully")

    token = data.token
    print(f"Verifying token: {token}")

    async with db.pool.acquire() as conn:
        # Find token
        row = await conn.fetchrow(
            """
            SELECT id, email_hmac, return_url, expires_at, initiator_id
            FROM auth_pending_logins
            WHERE token = $1
            """,
            token,
        )

        print(f"Database lookup result: {row}")

        if not row:
            print(f"Token not found in database: {token}")
            return JSONResponse(
                status_code=400,
                content={
                    "error": "invalid_token",
                    "message": "Invalid or expired token",
                },
            )

        # Check if expired
        if datetime.utcnow() > row["expires_at"]:
            return JSONResponse(
                status_code=400,
                content={
                    "error": "token_expired",
                    "message": "This link has expired",
                },
            )

        # Device binding: the token only completes in the originating browser.
        # Don't delete the row — the legit device can still use it.
        if not _initiator_matches(data.initiatorSecret, row["initiator_id"]):
            return _different_browser_response()

        email_hmac = row["email_hmac"]

        # Delete pending login
        await conn.execute("DELETE FROM auth_pending_logins WHERE id = $1", row["id"])

        return email_hmac, row["return_url"]


async def verify_registration_magic_link_handler(
    data: VerifyRegistrationMagicLinkData,
) -> JSONResponse | tuple[str, str | None] | None:

    # ensure pool initialized
    if db.pool is None:
        ok = await db.check_db_connection()
        if not ok:
            return JSONResponse(
                status_code=500, content={"message": "DB connection failed"}
            )

    token = data.token
    async with db.pool.acquire() as conn:
        row = await conn.fetchrow(
            """
            SELECT id, email_hmac, return_url, expires_at, initiator_id
            FROM auth_pending_registrations
            WHERE token = $1
            """,
            token,
        )
        if not row:
            return JSONResponse(
                status_code=400, content={"message": "Invalid or expired token"}
            )

        if datetime.utcnow() > row["expires_at"]:
            return JSONResponse(status_code=400, content={"message": "Token expired"})

        # Device binding (see verify_login). Don't delete on mismatch.
        if not _initiator_matches(data.initiatorSecret, row["initiator_id"]):
            return _different_browser_response()

        email_hmac = row["email_hmac"]

        # delete pending registration
        await conn.execute("DELETE FROM auth_pending_registrations WHERE id = $1", row["id"])

        return email_hmac, row["return_url"]


async def verify_short_code_handler(
    data: VerifyShortCodeData,
) -> JSONResponse | tuple[str, str | None, str] | None:
    """Verify a 6-character short code, purpose-agnostically.

    The waiting screen (browser A) does NOT know whether this is a login or a
    registration — that must stay identical until the email. So we search BOTH
    pending tables; the table that matches determines the outcome. Returns
    (email, return_url, purpose) on success, where purpose ∈ {login, registration}.
    """
    if db.pool is None:
        await db.init_pool()

    code = data.code.upper().strip()
    email_h = email_digest(data.email)  # the typed email, hashed for the lookup

    async with db.pool.acquire() as conn:
        # Find the most recent valid pending row across both tables (the login
        # table may hold several per email). Non-incrementing first, so the
        # device-binding check below can reject a wrong-device caller WITHOUT
        # burning the code's attempt budget.
        found = None
        table = None
        purpose = None
        for tbl, p in (
            ("auth_pending_logins", "login"),
            ("auth_pending_registrations", "registration"),
        ):
            candidate = await conn.fetchrow(
                f"""
                SELECT id, short_code, failed_attempts, initiator_id
                FROM {tbl}
                WHERE email_hmac = $1 AND short_code IS NOT NULL AND expires_at > now()
                ORDER BY created_at DESC, id DESC
                LIMIT 1
                """,
                email_h,
            )
            if candidate:
                found, table, purpose = candidate, tbl, p
                break

        if not found:
            return JSONResponse(
                status_code=400,
                content={"error": "invalid_code", "message": "Invalid or expired code"},
            )

        # Device binding: the code is only redeemable on the originating browser
        # (the waiting screen holds the initiator cookie). A caller who scraped
        # email+code from the preflight but lacks the cookie is rejected here,
        # before any attempt is counted.
        if not _initiator_matches(data.initiatorSecret, found["initiator_id"]):
            return _different_browser_response()

        # Atomic increment now that the device is authorized — protects the
        # compare against races.
        row = await conn.fetchrow(
            f"""
            UPDATE {table}
            SET failed_attempts = failed_attempts + 1
            WHERE id = $1
            RETURNING short_code, failed_attempts
            """,
            found["id"],
        )
        if not row:
            return JSONResponse(
                status_code=400,
                content={"error": "invalid_code", "message": "Invalid or expired code"},
            )

        # Check if too many attempts (already incremented)
        if row["failed_attempts"] > MAX_FAILED_ATTEMPTS:
            await conn.execute(f"DELETE FROM {table} WHERE id = $1", found["id"])
            return JSONResponse(
                status_code=400,
                content={"error": "too_many_attempts", "message": "Too many failed attempts. Please request a new code."},
            )

        # Constant-time comparison
        if not hmac.compare_digest(row["short_code"].upper(), code):
            remaining = MAX_FAILED_ATTEMPTS - row["failed_attempts"]
            if remaining <= 0:
                await conn.execute(f"DELETE FROM {table} WHERE id = $1", found["id"])
            return JSONResponse(
                status_code=400,
                content={
                    "error": "invalid_code",
                    "message": "Invalid code",
                    "remaining_attempts": max(remaining, 0),
                },
            )

        # Success — delete row (invalidates both magic link and short code)
        result = await conn.fetchrow(
            f"DELETE FROM {table} WHERE id = $1 RETURNING email_hmac, return_url", found["id"]
        )
        return (result["email_hmac"], result["return_url"], purpose) if result else None
