apiVersion: v1
kind: Namespace
metadata:
  name: poltr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pds-data
  namespace: poltr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-media
  namespace: poltr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allforone-postgres-data
  namespace: poltr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
