-- Adds translation support to the top-down taxonomy (app_topic_node).
--
-- Unlike arguments/comments, the taxonomy lives ONLY in the DB (generated by the
-- calculator) — there is no PDS/firehose. The appview translation worker writes
-- translations of the voter-facing fields (name + introduction) directly here.
-- `description` stays internal/German and is not translated.
--
-- Idempotent: safe to re-run.
--   psql "$APPVIEW_POSTGRES_URL" -f infra/scripts/postgres/migrate-topic-translations.sql

BEGIN;

ALTER TABLE app_topic_node
  ADD COLUMN IF NOT EXISTS langs              text[] NOT NULL DEFAULT ARRAY['de-CH'],
  ADD COLUMN IF NOT EXISTS translations       jsonb  NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS translation_status text   NOT NULL DEFAULT 'pending';

-- CHECK constraint (added separately so re-runs don't fail on duplicate).
DO $$ BEGIN
  ALTER TABLE app_topic_node
    ADD CONSTRAINT app_topic_node_translation_status_check
    CHECK (translation_status IN ('pending', 'partial', 'complete', 'manual_only'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Worker-Queue: nur unübersetzte Knoten.
CREATE INDEX IF NOT EXISTS app_topic_node_tx_status_idx ON app_topic_node (translation_status)
  WHERE translation_status IN ('pending', 'partial');

-- Quelltext geändert (Rebuild/CMS-Edit) → Übersetzungen verwerfen, Status zurück
-- auf 'pending', damit der Worker neu übersetzt.
CREATE OR REPLACE FUNCTION app_topic_node_reset_translations() RETURNS trigger AS $$
BEGIN
  IF NEW.name IS DISTINCT FROM OLD.name
     OR NEW.introduction IS DISTINCT FROM OLD.introduction THEN
    NEW.translations := '[]'::jsonb;
    NEW.translation_status := 'pending';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS app_topic_node_reset_translations_trg ON app_topic_node;
CREATE TRIGGER app_topic_node_reset_translations_trg
  BEFORE UPDATE ON app_topic_node
  FOR EACH ROW EXECUTE FUNCTION app_topic_node_reset_translations();

COMMIT;
